### ISSUE TITLE
Assets from bower

### ISSUE THREAD

**Issue by disem** [yii2mod/yii2-chosen-select#1]
Chosen плагин есть в бовере, можно ставить оттуда.

**Comment by ihorchepurnyi** [comment]
Автор экстеншена написал вот что:
Chosen does not currently support command-line bower install chosen installation.

**Comment by devleaks** [comment]
I was about to file the same enhancement request, and saw this.
Please have a look at https://github.com/drmonty/chosen.
Thanks. Pierre

**Comment by ihorchepurnyi** [comment]
Thanks, now we used your package.
