### ISSUE TITLE
return vs echo

### ISSUE THREAD

**Issue by nadar** [yii2mod/yii2-chosen-select#11]
Hi

Whats the reason to use echo instead of return? 

https://github.com/yii2mod/yii2-chosen-select/blob/master/ChosenSelect.php#L66

I think this is considered bad practice and also disables the option to passed the content into a variable. Therefore i would suggest register the assets before and then return the content `return Html::..`.

Would you accept a PR or its there a specific reason to do so?

**Comment by nadar** [comment]
*bump* 😄

**Comment by nadar** [comment]
:crying_cat_face:

**Comment by ihorchepurnyi** [comment]
Hi @nadar, I'm sorry for late reply. Could you please create a PR for it?
